@baseUrl = http://localhost:5000
###
POST {{baseUrl}}/usuarios
Content-Type: application/json

{
    "nome": "Felipe Jhordan1",
    "email": "felipejordan.alves@gmail.com"
}

###
GET {{baseUrl}}/usuarios
Content-Type: application/json

###
GET {{baseUrl}}/usuarios/1
Content-Type: application/json 

